### PR TITLE
Fix corner case with namespace splitting and mild refactoring

### PR DESCRIPTION
**Pull request by facelessuser**
Fix corner case with namespace splitting and refactor selector
loading.

### CODE REVIEW

**Comment by facelessuser** [comment]
@gir-bot lgtm

**Comment by JackDandy** [comment]
Hi,

As this commit is a bug fix (albeit, a corner case) and not py3 dependent, can you consider cherry picking this commit over to the 1.9.X py2 branch?

**Comment by facelessuser** [comment]
Like you said, it really is a corner case. One I don't expect people to hit...at least not the average person :slightly_smiling_face:. I'll consider it. I'm not sure it qualifies as a big bug, but if I did cherry pick this, it would literally be the last release.

**Comment by JackDandy** [comment]
ah okay, then i suggest waiting until the last py2 version is released in April, and do a rollup of pure fixes at that point in time ;)

**Comment by JackDandy** [comment]
> but if I did cherry pick this, it would literally be the last release.

ah okay, then i suggest waiting until the last py2 version is released in April, and do a rollup of pure fixes at that point in time ;)

**Comment by facelessuser** [comment]
@JackDandy, I've decided to do a 1.9.6 in April. You can track progress here: #187. If I miss anything, that is where to make a request for the appropriate cherry pick. I think I have everything relevant in the the 1.9.X branch, but if I missed anything, let me know.

**Pull request merged**
