### PR TITLE
Add support for Python 3.11

### PR DESCRIPTION
**Pull request by hugovk**
Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk) 🚀 

[image](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)

### CODE REVIEW

**Comment by facelessuser** [comment]
I appreciate the work on this. We'll have to investigate why the Windows `nolxml` and `nohtml5lib` tests are failing before we can merge. I don't see anything specifically wrong with what you've submitted, but all the same, they are failing 😞.

**Comment by facelessuser** [comment]
It may simply be that lxml is not properly supported on Windows yet for PY 3.11. If that is the case, we may need to set those back to PY 3.10.

**Comment by hugovk** [comment]
Aha, that's it, lxml doesn't have Windows wheels for 3.11 yet: https://bugs.launchpad.net/lxml/+bug/1977998, https://github.com/lxml/lxml/pull/355

Will revert those bits.

**Comment by facelessuser** [comment]
I think I see the issue. The new lxml does not ship a Windows wheel for 3.11. We fail when trying to build lxml. In our normal 311 tests, it seems we fail building 3.11 as well, but don't fail the tests for it and continue on. I will merge this, but I'll have to play with the tests. Most likely, we just can't test PY 3.11 with lxml right now. I may have to reflect that in our tests until lxml works on Windows with PY 3.11.

**Comment by facelessuser** [comment]
@gir-bot lgtm

**Comment by hugovk** [comment]
I pushed this just _after_ merge :) https://github.com/hugovk/soupsieve/commit/3cfa4eb3f3468e6fd7215e74c25a8f34f0a7f237

**Comment by facelessuser** [comment]
@hugovk Thanks. I think what I'll do though is just create a special requirement file that doesn't install lxml when we don't want to test lxml. It's kind of silly that I'm I'm installing it just to uninstall it for those specific tests. Additionally, I want to explore if we can get the dependencies right to allow testing on Windows and PY3.11. It seems to be missing a library during the build. If this can't be resolved, I'll probably just limit testing to 3.10 for Windows for now.

**Comment by facelessuser** [comment]
It's all working on the main branch now. Thanks for your work!

**Comment by hugovk** [comment]
Great, and thank you too!

**Pull request merged**
