### PR TITLE
perf: don't import bs4 in every `is_...` function

### PR DESCRIPTION
**Pull request by akx**
In my app, this makes `is_tag` (the third hottest function according to profiling) about 24% faster:

func | ncalls | time | owntime
---- | ----- | ---- | --------
master/is_tag | 2054073 | 1566 | 1179
perf-istag/is_tag | 2054073 | 1191 | 775

I assume unpacking all of the classes from `bs4` might make things a little faster still, but it's probably not worth the mess?

### CODE REVIEW

**Comment by facelessuser** [comment]
This was actually meant to reduce problems with circular imports. Bs4 imports soupsieve who imports bs4. We did this to ensure we wait until bs4 is fully imported before trying to to import them.

**Comment by facelessuser** [comment]
I am concerned this could cause issues. I believe I did run into some which forced me to do so. If this was included in the bs4 lib, this probably wouldn't be necessary, but it was done as an external module specifically to make it attractive enough to have bs4 adopt it.

The select implementation prior to soupsieve suffered greatly from inadequate logic, and was designed in a confusing and difficult manner to add new features to. The author of bs4 stopped trying to fix bugs in it and pushed maintenance on to the community to fix the bugs, which just didn't happen. So an external library that he didn't have to maintain is what made it attractive.

**Comment by facelessuser** [comment]
@gir-bot add needs-decision

**Comment by facelessuser** [comment]
@gir-bot add S: needs-decision

**Comment by facelessuser** [comment]
I'm having some trouble creating an error due to the circular import. Most likely because we don't seem to actually attempt to use the module until everything is imported. I might be okay with this. 

If we do this, I think instead of simply setting `bs4` to `None`, we should raise a user warning that bs4 could not be imported. As long as all other tests pass, we can probably just add `# pragma: no cover` to the exception to keep coverage from failing.

**Comment by akx** [comment]
> If we do this, I think instead of simply setting `bs4` to `None`, we should raise a user warning that bs4 could not be imported. 

I'm not sure that's worth the warning noise. After all, one will eventually get a `NoneType has no attribute something` error when attempting to use the `is...` methods without bs4 installed? 

> As long as all other tests pass, we can probably just add `# pragma: no cover` to the exception to keep coverage from failing.

Added.

**Comment by facelessuser** [comment]
If we were going to throw an exception, I'd rather throw it as soon as possible, and in that case we should throw the import exception. So maybe we should remove the try strong the import.

**Comment by facelessuser** [comment]
If, per chance, we find in some environments this causes issues (hopefully it doesn't) we would probably have to revert this change. I'm hoping there will be no unpleasant side effects, but I think this should be fine for now once the above change is addressed.

**Comment by facelessuser** [comment]
Can you post the script you use to gather your metrics? I'm interested in exploring this particular case in a couple of different ways.

**Comment by akx** [comment]
> Can you post the script you use to gather your metrics? I'm interested in exploring this particular case in a couple of different ways.

I'm just using [PyCharm](https://www.jetbrains.com/pycharm/)'s Profile Run button here, but it's basically running `python -m cProfile ...` with a fancier output. I can't presently share the script or data I'm actually scraping here, but it's mostly

```python
def find_text(soup: bs4.Tag, selector) -> Optional[str]:
    el = soup.select_one(selector)
    if el:
        return el.text.strip()
    return None
```

**Comment by akx** [comment]
> If we were going to throw an exception, I'd rather throw it as soon as possible, and in that case we should throw the import exception. So maybe we should remove the try around the import.

Is `soupsieve` even technically usable at all without a `bs4` installed? If you think not, then sure. Otherwise I'd like to keep it there, in case some esoteric downstream user is using bits of soupsieve for something bs4-less.

**Comment by facelessuser** [comment]
In it's current state it requires bs4, and an import error is more descriptive of the actual issue than an attributes error in a none type object. So I would prefer that.

As far as profiling, how many times did it run the original command? Obviously the first run will take longer door to the install import, but I suspect subsequent runs would be much faster.

**Comment by akx** [comment]
> In it's current state it requires bs4, and an import error is more descriptive of the actual issue than an attributes error in a none type object. So I would prefer that.

That's perfectly clear then. I'll remove the guard :)
 
> As far as profiling, how many times did it run the original command? Obviously the first run will take longer door to the install import, but I suspect subsequent runs would be much faster.

The script I profiled scrapes some thousands of HTML files (which is reflected in the 2 million or so ncalls). Also, the script imports bs4 beforehand anyway. I suspect it's just that a function with `import` simply has to do more work:


```
>>> import os
>>> import dis
>>>
>>> def x():
...   os.getpid()
...
>>> def y():
...   import os
...   os.getpid()
...
>>> dis.dis(x)
  2           0 LOAD_GLOBAL              0 (os)
              2 LOAD_METHOD              1 (getpid)
              4 CALL_METHOD              0
              6 POP_TOP
              8 LOAD_CONST               0 (None)
             10 RETURN_VALUE
>>> dis.dis(y)
  2           0 LOAD_CONST               1 (0)
              2 LOAD_CONST               0 (None)
              4 IMPORT_NAME              0 (os)
              6 STORE_FAST               0 (os)

  3           8 LOAD_FAST                0 (os)
             10 LOAD_METHOD              1 (getpid)
             12 CALL_METHOD              0
             14 POP_TOP
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE
>>>
```

In particular, `IMPORT_NAME`:
* [does a builtins lookup for `__import__`, either calls it, or](
https://github.com/python/cpython/blob/5f4b229df7812f1788287095eb6b138bb21876a4/Python/ceval.c#L5199-L5240)
* [as a fast path, directly uses `PyImport_ImportModuleLevelObject`](https://github.com/python/cpython/blob/5f4b229df7812f1788287095eb6b138bb21876a4/Python/import.c#L1809), which isn't a simple function at all...
, what with the `IMPORT_NAME` opcode having to do a `sys.modules` lookup or whatnot:

**Comment by facelessuser** [comment]
I'm wondering if something like this may be better as I 'm still concerned that in some embedded environments that this circular import may cause problems. This would reduce the redundant importing to simply a check for None (though I guess we could check for a falsely status as instead) . The import of bs4 is still deferred with a lesser impact.

```diff
diff --git a/soupsieve/css_match.py b/soupsieve/css_match.py
index b35e0e6..42bb1d9 100644
--- a/soupsieve/css_match.py
+++ b/soupsieve/css_match.py
@@ -5,6 +5,8 @@ import re
 from .import css_types as ct
 import unicodedata
 
+_bs4 = None
+
 # Empty tag pattern (whitespace okay)
 RE_NOT_EMPTY = re.compile('[^ \t\r\n\f]')
 
@@ -53,6 +55,11 @@ FEB_LEAP_MONTH = 29
 DAYS_IN_WEEK = 7
 
 
+def import_bs4():
+    global _bs4
+    print('done')
+    _bs4 = __import__('bs4')
+
 class _FakeParent(object):
     """
     Fake parent class.
@@ -88,50 +95,64 @@ class _DocumentNav(object):
     def is_doc(obj):
         """Is `BeautifulSoup` object."""
 
-        import bs4
-        return isinstance(obj, bs4.BeautifulSoup)
+        if _bs4 is None:
+            import_bs4()
+
+        return isinstance(obj, _bs4.BeautifulSoup)
 
     @staticmethod
     def is_tag(obj):
         """Is tag."""
 
-        import bs4
-        return isinstance(obj, bs4.Tag)
+        if _bs4 is None:
+            import_bs4()
+
+        return isinstance(obj, _bs4.Tag)
 
     @staticmethod
     def is_declaration(obj):  # pragma: no cover
         """Is declaration."""
 
-        import bs4
-        return isinstance(obj, bs4.Declaration)
+        if _bs4 is None:
+            import_bs4()
+
+        return isinstance(obj, _bs4.Declaration)
 
     @staticmethod
     def is_cdata(obj):
         """Is CDATA."""
 
-        import bs4
-        return isinstance(obj, bs4.CData)
+        if _bs4 is None:
+            import_bs4()
+
+        return isinstance(obj, _bs4.CData)
 
     @staticmethod
     def is_processing_instruction(obj):  # pragma: no cover
         """Is processing instruction."""
 
-        import bs4
-        return isinstance(obj, bs4.ProcessingInstruction)
+        if _bs4 is None:
+            import_bs4()
+
+        return isinstance(obj, _bs4.ProcessingInstruction)
 
     @staticmethod
     def is_navigable_string(obj):
         """Is navigable string."""
 
-        import bs4
-        return isinstance(obj, bs4.NavigableString)
+        if _bs4 is None:
+            import_bs4()
+
+        return isinstance(obj, _bs4.NavigableString)
 
     @staticmethod
     def is_special_string(obj):
         """Is special string."""
 
-        import bs4
-        return isinstance(obj, (bs4.Comment, bs4.Declaration, bs4.CData, bs4.ProcessingInstruction, bs4.Doctype))
+        if _bs4 is None:
+            import_bs4()
+
+        return isinstance(obj, (_bs4.Comment, _bs4.Declaration, _bs4.CData, _bs4.ProcessingInstruction, _bs4.Doctype))
 
     @classmethod
     def is_content_string(cls, obj):
```

**Comment by akx** [comment]
How about a lazy-import proxy for bs4 instead? Dry-coded, etc:

```python
class Bs4ModuleProxy:
    bs4 = None
    def __getattr__(self, key):
        if not self.bs4:
            self.bs4 = __import__("bs4")
        val = getattr(self.bs4, key)
        setattr(self, key, val)
        return val

bs4 = Bs4ModuleProxy()
```

To be honest though, I wonder if this all is becoming too complex for a simple optimization 😁

**Comment by facelessuser** [comment]
We could, but I don't see what we specifically gain with the added complexity of the proxy class. With the previous suggestion we delay the import and avoid the time spent in import. I don't think we also need the overhead of wrapping the gettattr calls too.

**Comment by facelessuser** [comment]
If we just wanted to reduce the redundant none checks, we could simply move them into the import function.

**Comment by facelessuser** [comment]
If we really wanted to have a lazy loader, something like this may work as it will only be called on the first time:

```py
class _LazyLoadBs4:
    """
    Lazy import of Beautiful Soup.

    Avoids issues related to circular import as Beautiful Soup
    requires `soupsieve` which requires `bs4`.
    """

    def __getattr__(self, key):
        """Load Beautiful Soup to our global variable on demand."""

        global _bs4
        _bs4 = __import__("bs4")
        return getattr(_bs4, key)


_bs4 = _LazyLoadBs4()
```
I'm not sure if it is needed, but if there was a concern for race conditions, we could simply have a lock in the `__getattr__` method. I'm pretty sure assigning globals is an atomic operation though.

**Comment by facelessuser** [comment]
I think we'll go with what you have and adjust only after complaints are found (if any are found).

@gir-bot lgtm

**Pull request merged**
